const mongoose = require("mongoose");

const companySchema = new mongoose.Schema({
  Symbol: String,
  "52WeekLow": String,
  "52WeekHigh": String,
  "50DayMovingAverage": String,
  "200DayMovingAverage": String,
  Address: String,
  AnalystRatingBuy: String,
  AnalystRatingHold: String,
  AnalystRatingSell: String,
  AnalystRatingStrongBuy: String,
  AnalystRatingStrongSell: String,
  AnalystTargetPrice: String,
  AssetType: String,
  Beta: String,
  BookValue: String,
  CIK: String,
  Country: String,
  Currency: String,
  Description: String,
  DilutedEPSTTM: String,
  DividendDate: String,
  DividendPerShare: String,
  DividendYield: String,
  EBITDA: String,
  EPS: String,
  EVToEBITDA: String,
  EVToRevenue: String,
  ExDividendDate: String,
  Exchange: String,
  FiscalYearEnd: String,
  ForwardPE: String,
  GrossProfitTTM: String,
  Industry: String,
  LatestQuarter: String,
  MarketCapitalization: String,
  Name: String,
  OfficialSite: String,
  OperatingMarginTTM: String,
  PEGRatio: String,
  PERatio: String,
  PriceToBookRatio: String,
  PriceToSalesRatioTTM: String,
  ProfitMargin: String,
  QuarterlyEarningsGrowthYOY: String,
  QuarterlyRevenueGrowthYOY: String,
  ReturnOnAssetsTTM: String,
  ReturnOnEquityTTM: String,
  RevenuePerShareTTM: String,
  RevenueTTM: String,
  Sector: String,
  SharesOutstanding: String,
  TrailingPE: String,
},{
      collection: "COMPANIES"
});

module.exports = mongoose.model("Company", companySchema);